"""v2.8.4 — R0, the reach diagnosis for the (T, omega_des) cascade. MEASUREMENT ONLY.

SUBJECT. `src/frameworks/mppi/cascade_rate.py`. `cascade.py` (the v5 a_des plan) is NOT the subject and
is not imported. The interface, the inner rate loop, the post-allocation per-rotor clip, the collision
predicate, the cost and the full RK4 rotor-thrust simulation plant are UNCHANGED and are CALLED here,
never re-implemented and never edited.

ADDITIVE AND READ-ONLY TOWARD EXISTING BEHAVIOUR. Nothing in this module is imported by any existing run;
it only reads shipped objects and reuses `src/frameworks/mppi/parity_rate.py`'s already-built measurement
plumbing. It writes `data/runs/v2.8.4/mppi_reach/**` and nothing else.

WHAT IS ALREADY MEASURED AND IS ONLY CITED HERE
-----------------------------------------------
Five of R0's six quantities are already computed by the parity harness on this exact scene and are read
back out of its artifact rather than recomputed:

    data/runs/v2.8.4/mppi_parity/item_E_smoke_scene__run{1,2}.json
      leg `ours_shipped_ou_relative`  ->  `exponent_spread_*` / `exponent_frac_gt_745`   (R0 quantity 2)
                                          `per_step.ess`                                 (R0 quantity 3)
                                          `nominal_increment_norm`                       (R0 quantity 4)
                                          `cost_shares_episode` / `_per_step_p50`        (R0 quantity 5)
                                          `argmin_rollout_closest_approach_m` and
                                          `weighted_average_rollout_closest_approach_m`  (R0 quantity 6)

R0 quantity 1 — "is the min-cost baseline rho subtracted at all" — is a CODE fact, not a run:
`src/frameworks/mppi/cascade_rate.py:692`, `shifted = cost - cost.min(dim=1, keepdim=True).values`, with
the reference doing the same at `pytorch_mppi/mppi.py:255`. It needs no measurement and none is taken.

WHAT THIS MODULE ADDS — the two things the artifact does not carry
------------------------------------------------------------------
N1. THE COST-ALIGNMENT PROBE. The question R0 exists to settle is whether the failure is in the OPTIMIZER
    (the weighting / the update / the search distribution) or OUTSIDE it (the cost, the model, the plant).
    The decisive measurement is: does a (T, omega) sequence that DOES reach score BETTER under this very
    cost than the 1024 sequences the sampler drew?

    The reaching sequence is generated by the deterministic law the smoke already recorded as reaching
    (`smoke_cascade_rate.shipped_pd_command`, closest approach 0.0032596218381637457 m vs goal_radius
    0.15, `data/runs/v2.8.4/mppi_cascaded/smoke.json` check b1), rolled forward IN THE PLANNER'S OWN MODEL
    over the same horizon, so it is an admissible plan in exactly the space the sampler searches.

    ASYMMETRY DECLARED AT THE POINT OF USE: this sequence reads the GOAL and the STATE and nothing else —
    `a_des = -kp_pos (p - g) - kd_pos v` with the gains read off the system object. It is not a reference
    trajectory, not a global plan and not a map; no waypoint, path or precomputed trajectory exists
    anywhere in this module.

    It is then scored through THE SAME wired callbacks the parity harness validated against our own
    `_rollout_cost` (`parity_rate.WiredCallbacks`, agreement bit-identical over the episode), so the
    comparison is cost-to-cost with no re-implementation.

      * if the deterministic sequence's cost is BELOW the sampler's minimum, the cost ranks reaching
        correctly and the sampler is simply not drawing it -> the failure IS in the optimizer's search
        distribution, and a seeded rollout (R2) is the targeted rung;
      * if it is ABOVE, the cost prefers something other than reaching -> the failure is NOT in the
        optimizer and this module stops and says so.

N2. THE COLLISION-SHARE ATTRIBUTION. `item_E` records a 0.754 collision share on an OBSTACLE-FREE scene.
    The scene's only obstacle slot is inactive (`smoke_cascade_rate.straight_line_scene:66`), so every
    charge must come from the band leg of the SAME predicate the eval harness resolves outcomes with
    (`cost.collision_mask:279-284`, `|p_z| >= env.band_collision_limit`). This module counts, per control
    step, what fraction of the drawn samples are charged at all, at which horizon index the first charge
    lands, and the |z| the samples reach — so the share is attributed to a mechanism rather than named.

N3. THE DELEGATION ERROR IN THE CLOSED LOOP. `smoke.json` check (g) measured the planner-model-vs-plant
    divergence on RANDOM states under SAMPLER draws. Here the same two quantities are measured on the
    states the closed loop actually visits: the executed rate command against the plant's realised body
    rate. This distinguishes "the plan is bad" from "the plan is fine and the plant does not follow it".

Every constant is read from the system object or the config. No pool is touched, no cell is selected, no
threshold is registered, nothing is ranked and nothing is promoted.

Run:  CUDA_VISIBLE_DEVICES="" python -m src.frameworks.mppi.reach_r0
"""
from __future__ import annotations

import argparse
import json
import os
import time
from pathlib import Path
from typing import Any, Mapping

import torch

from src._version import __version__
from src.common.observation import scene_goal_tensor
from src.common.rk4 import rk4_step
from src.common.system import System
from src.envs.scene_batch import batch_scenes
from src.frameworks.mppi import smoke_cascade_rate as smoke
from src.frameworks.mppi.cascade_rate import RateCascadeController, _W
from src.frameworks.mppi.cost import collision_mask
from src.frameworks.mppi.evaluate_mppi import REPO, effective_config, load_mppi_config
from src.frameworks.mppi.parity_rate import (
    IMMUTABLE_DIRS,
    WiredCallbacks,
    build,
    our_noise,
    roll_block,
    roll_one,
    summarise,
    weights_from,
)


Tensor = torch.Tensor

OUT_DIR = REPO / "data/runs/v2.8.4/mppi_reach"

# READ-ONLY, recorded before and after. `parity_rate.IMMUTABLE_DIRS` carries eight; the mission adds
# mppi_parity itself, which this module also only ever reads.
READONLY_DIRS = tuple(IMMUTABLE_DIRS) + (REPO / "data/runs/v2.8.4/mppi_parity",)

PARITY_ARTIFACTS = (
    REPO / "data/runs/v2.8.4/mppi_parity/item_E_smoke_scene__run1.json",
    REPO / "data/runs/v2.8.4/mppi_parity/item_E_smoke_scene__run2.json",
)

MIN_COST_BASELINE_SITE = "src/frameworks/mppi/cascade_rate.py:692"


def proc_state() -> dict[str, Any]:
    pid = os.getpid()
    state = ""
    try:
        for line in Path(f"/proc/{pid}/status").read_text(encoding="utf-8").splitlines():
            if line.startswith("State:"):
                state = line.split(":", 1)[1].strip()
                break
    except OSError:                                                          # pragma: no cover
        state = "unavailable"
    return {"pid": pid, "ppid": os.getppid(), "proc_state": state,
            "launched_with": "plain subprocess; NO setsid and NO nohup"}


def dir_state() -> dict[str, Any]:
    out: dict[str, Any] = {}
    for p in READONLY_DIRS:
        st = p.stat()
        deep = max((q.stat().st_mtime_ns for q in p.rglob("*")), default=0)
        out[str(p.relative_to(REPO))] = {
            "mtime_ns": st.st_mtime_ns,
            "mtime_iso": time.strftime("%Y-%m-%dT%H:%M:%S", time.localtime(st.st_mtime))
                         + f".{st.st_mtime_ns % 1_000_000_000:09d}",
            "n_entries": len(list(p.iterdir())),
            "deepest_file_mtime_ns": deep,
        }
    return out


def write_report(name: str, report: dict[str, Any]) -> Path:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    path = OUT_DIR / name
    if path.exists():
        path = path.with_name(f"{path.stem}__{time.strftime('%H%M%S')}{path.suffix}")
    path.write_text(json.dumps(report, indent=2, default=str) + "\n", encoding="utf-8")
    print(f"wrote {path}", flush=True)
    return path


# =================================================================================================
# the deterministic sequence, rolled in THE PLANNER'S OWN MODEL
# =================================================================================================
@torch.no_grad()
def deterministic_sequence(
    system: System, controller: RateCascadeController, x: Tensor, goal: Tensor, horizon: int
) -> Tensor:
    """The (T, omega_des) sequence the SHIPPED deterministic law would command over one horizon, rolled
    forward in `_RatePlannerModel` — the planner's own model, the same one every sampled rollout uses.

    `smoke_cascade_rate.shipped_pd_command` is CALLED, not re-implemented: it is `System.lqr_action`'s own
    outer loop written in this interface, and `smoke.json` check (f) records it reproducing
    `system.lqr_action` to 0.0 N. The planner's `rate_limit` and the planner's low-pass are applied
    exactly as `cascade_rate.py:610` and `:672-673` apply them, so the result is an admissible plan in the
    space the sampler searches — nothing more.

    ASYMMETRY, NAMED HERE AT THE POINT OF USE: the law reads the GOAL and the STATE only. It is not a
    reference trajectory, not a global planner and not a map.

    Returns [H, 4].
    """
    beta = controller.lowpass_beta
    state = x.clone()
    rate_f = state[:, _W].clone()
    entries = []
    for _ in range(horizon):
        thrust, omega_des = smoke.shipped_pd_command(system, state, goal)
        command = controller.rate_limit(torch.cat([thrust, omega_des], dim=-1))     # [1,4]
        entries.append(command[0].clone())
        rate_f = beta * rate_f + (1.0 - beta) * command[:, 1:]
        state = torch.cat([state[:, :10], rate_f], dim=1)
        state = rk4_step(controller.planner, state, command, controller.dt)
    return torch.stack(entries, dim=0)


# =================================================================================================
# N2 — where the collision charge on an obstacle-free scene comes from
# =================================================================================================
@torch.no_grad()
def band_attribution(
    system: System, controller: RateCascadeController, x: Tensor, sampled: Tensor,
    centers: Tensor, radii: Tensor, active: Tensor,
) -> dict[str, float]:
    """Re-roll the drawn samples through the PLANNER'S model, applying the SAME `collision_mask` the
    rollout charges C_crash with, and record what fraction of samples are charged, at which horizon index
    the first charge lands and how far in |z| the samples travel. `sampled` is [N, H, 4].

    The obstacle leg is evaluated too and reported separately, so "the charge is the band" is measured
    rather than asserted: on this scene the single obstacle slot is inactive.
    """
    n, horizon, _ = sampled.shape
    beta = controller.lowpass_beta
    state = x.expand(n, -1).clone()
    rate_f = state[:, _W].clone()
    dead = torch.zeros(n, dtype=torch.bool, device=controller.device)
    first_index = torch.full((n,), -1, dtype=torch.long, device=controller.device)
    max_abs_z = torch.zeros(n, dtype=controller.dtype, device=controller.device)
    obstacle_hits = torch.zeros(n, dtype=torch.bool, device=controller.device)
    for k in range(horizon):
        command = sampled[:, k]
        rate_f = beta * rate_f + (1.0 - beta) * command[:, 1:]
        state = torch.cat([state[:, :10], rate_f], dim=1)
        nxt = rk4_step(controller.planner, state, command, controller.dt)
        state = torch.where(dead.unsqueeze(-1), state, nxt)
        position = system.position(state).view(1, n, -1)
        collided = collision_mask(position, centers, radii, active, controller.cost).reshape(n)
        # the OBSTACLE leg alone, so the band's contribution is isolated by difference
        pos_o = position[..., : centers.shape[-1]]
        distance = torch.linalg.norm(pos_o.unsqueeze(-2) - centers.unsqueeze(-3), dim=-1)
        obstacle = ((distance < radii.unsqueeze(-2)) & active.unsqueeze(-2)).any(dim=-1).reshape(n)
        obstacle_hits = obstacle_hits | obstacle
        newly = collided & ~dead
        first_index = torch.where(newly, torch.full_like(first_index, k), first_index)
        dead = dead | collided
        max_abs_z = torch.maximum(max_abs_z, system.position(state)[:, 2].abs())
    charged = first_index >= 0
    idx = first_index[charged].to(controller.dtype)
    return {
        "frac_samples_charged": float(charged.double().mean().item()),
        "frac_samples_charged_by_obstacle_leg": float(obstacle_hits.double().mean().item()),
        "first_charge_horizon_index_p50": float(idx.median().item()) if bool(charged.any()) else -1.0,
        "first_charge_horizon_index_min": float(idx.min().item()) if bool(charged.any()) else -1.0,
        "max_abs_z_p50_m": float(max_abs_z.median().item()),
        "max_abs_z_p95_m": float(max_abs_z.quantile(0.95).item()),
        "max_abs_z_max_m": float(max_abs_z.max().item()),
    }


# =================================================================================================
# the R0 episode
# =================================================================================================
@torch.no_grad()
def r0_episode(mppi_config: dict[str, Any], config: dict[str, Any], *, n_samples: int) -> dict[str, Any]:
    device, dtype = torch.device("cpu"), torch.float64
    smoke_cfg = mppi_config["cascaded"]["smoke"]
    seed = int(mppi_config["cascaded"]["scale"]["seed"])
    dt = float(config["env"]["dt"])
    goal_radius = float(config["env"]["goal_radius"])
    band_limit = float(config["env"]["band_collision_limit"])

    # THE SHIPPED CASCADED CONFIGURATION, exactly as item E's row A built it: OU noise, relative lambda.
    system, _, controller = build(
        mppi_config, config, n_samples=n_samples, noise="ou", lam_mode="relative",
        device=device, dtype=dtype,
    )
    scene = smoke.straight_line_scene(
        system, [float(v) for v in smoke_cfg["straight_line"]["offset"]], dtype
    )
    batched = batch_scenes([scene], device=device, dtype=dtype)
    x = smoke.level_state(system, torch.as_tensor(scene.start, dtype=dtype).view(1, 3), dtype)
    goal = torch.as_tensor(scene.goal, dtype=dtype).view(1, 3)
    seconds = float(smoke_cfg["straight_line"]["seconds"])
    n_steps = int(round(seconds / dt))

    controller.reset(1)
    controller.generator.manual_seed(seed)
    centers, radii, active = controller._scene_tensors(batched)
    goal_row = scene_goal_tensor(batched, x)
    k = int(controller.params.n_samples)
    horizon = int(controller.params.horizon)

    def cb_factory(m: int) -> WiredCallbacks:
        return WiredCallbacks(controller, system, goal_row, centers, radii, active, m)

    record: dict[str, list] = {key: [] for key in (
        "distance_m", "ess", "lam", "cost_min", "cost_p50", "cost_std",
        "cost_deterministic", "cost_nominal_out", "rank_of_deterministic",
        "deterministic_beats_sample_min", "closest_deterministic_m", "closest_argmin_m",
        "closest_nominal_out_m", "band", "rate_tracking_err", "rate_cmd_norm", "rate_plant_norm",
        "abs_z_m", "speed_m_s",
    )}

    for _ in range(n_steps):
        plan_before = controller.plan.clone()
        base = controller.absolute(plan_before)
        noise_draw = our_noise(controller, 1)                       # what `act` is about to draw
        sampled = controller.rate_limit(base.unsqueeze(1) + noise_draw)
        effective_noise = sampled - base.unsqueeze(1)
        cost_internal, _ = controller._rollout_cost(x, sampled, goal_row, centers, radii, active)
        cost = cost_internal[0]

        # ---- N1: the deterministic sequence, scored by THE SAME cost -----------------------------
        det = deterministic_sequence(system, controller, x, goal, horizon)          # [H,4]
        cb_one = cb_factory(1)
        cost_det = float(roll_block(cb_one, x, det.unsqueeze(0))[0].item())
        closest_det = float(cb_one.min_dist.min().item())

        # ---- N2: where the collision charge comes from -------------------------------------------
        record["band"].append(
            band_attribution(system, controller, x, sampled[0], centers, radii, active)
        )

        action = controller.act(x, batched)
        lam_eff = float(controller.last_lam_eff[0].item())
        ess = float(controller.last_ess[0].item())
        weight, _, _ = weights_from(cost, lam_eff, dtype)
        degenerate = bool(controller.last_degenerate[0].item())
        update = plan_before[0] + (weight.view(-1, 1, 1) * effective_noise[0]).sum(dim=0)
        if degenerate:
            update = plan_before[0]
        nominal_out = controller.absolute(update)
        cb_two = cb_factory(1)
        cost_nominal = float(roll_block(cb_two, x, nominal_out.unsqueeze(0))[0].item())

        argmin = int(cost.argmin().item())
        rank = int((cost < cost_det).sum().item())          # how many of the K samples beat it
        record["cost_min"].append(float(cost.min().item()))
        record["cost_p50"].append(float(cost.median().item()))
        record["cost_std"].append(float(cost.std().item()))
        record["cost_deterministic"].append(cost_det)
        record["cost_nominal_out"].append(cost_nominal)
        record["rank_of_deterministic"].append(rank)
        record["deterministic_beats_sample_min"].append(bool(cost_det < float(cost.min().item())))
        record["closest_deterministic_m"].append(closest_det)
        record["closest_argmin_m"].append(roll_one(cb_factory, sampled[0][argmin], x))
        record["closest_nominal_out_m"].append(roll_one(cb_factory, nominal_out, x))
        record["ess"].append(ess)
        record["lam"].append(lam_eff)

        # ---- N3: the delegation error on the states the closed loop actually visits ---------------
        # the EXECUTED command, formed exactly as cascade_rate.py:716-720 forms it from the updated plan
        head = controller.rate_limit(nominal_out[0].view(1, -1))
        rate_cmd = controller.lowpass_beta * x[:, _W] + (1.0 - controller.lowpass_beta) * head[:, 1:]
        record["rate_cmd_norm"].append(float(torch.linalg.norm(rate_cmd).item()))
        x = rk4_step(system, x, action, dt)
        record["rate_plant_norm"].append(float(system.angular_rate(x).item()))
        record["rate_tracking_err"].append(float(torch.linalg.norm(x[:, _W] - rate_cmd).item()))
        record["distance_m"].append(float(torch.linalg.norm(system.position(x) - goal).item()))
        record["abs_z_m"].append(float(system.position(x)[0, 2].abs().item()))
        record["speed_m_s"].append(float(system.speed(x).item()))

    bands = record["band"]
    n_beats = sum(record["deterministic_beats_sample_min"])
    return {
        "what": "R0 — the reach diagnosis on the obstacle-free straight-line scene, shipped cascaded "
                "configuration (OU noise, relative lambda), closed loop on the FULL RK4 rotor-thrust "
                "plant. MEASUREMENT ONLY.",
        "variant": "cascaded_rate",
        "configuration": {
            "N_samples": k, "horizon": horizon, "dt": controller.dt,
            "noise": controller.params.noise, "lam_mode": controller.params.lam_mode,
            "sigma_per_rotor_equivalent_N": float(controller.params.sigma),
            "sigma_per_channel": [float(v) for v in controller.sigma_channel.tolist()],
            "k_rate": controller.k_rate, "omega_max_read_from_system": controller.omega_max,
            "goal_radius_read_from_config": goal_radius,
            "band_collision_limit_read_from_config": band_limit,
            "c_crash": controller.cost.c_crash,
            "n_control_steps": n_steps, "seconds": seconds,
            "scene": "the smoke's obstacle-free straight-line scene "
                     "(smoke_cascade_rate.straight_line_scene:66); the single obstacle slot is INACTIVE",
        },
        "closed_loop": {
            "closest_approach_m": min(record["distance_m"]),
            "final_distance_m": record["distance_m"][-1],
            "reaches_position_radius": bool(min(record["distance_m"]) <= goal_radius),
            "abs_z_m": summarise(record["abs_z_m"]),
            "speed_m_s": summarise(record["speed_m_s"]),
        },
        "N1_cost_alignment": {
            "question": "does a (T, omega) sequence that DOES reach score BETTER under this cost than the "
                        "K sequences the sampler drew?",
            "deterministic_sequence": "smoke_cascade_rate.shipped_pd_command rolled forward in the "
                                      "PLANNER'S OWN model over the same horizon, rate-limited and "
                                      "low-passed exactly as cascade_rate.py:610,672-673 do",
            "asymmetry_declared_here": "the law reads the GOAL and the STATE only "
                                       "(a_des = -kp_pos (p-g) - kd_pos v, gains read off the system "
                                       "object). NO reference trajectory, NO global planner, NO map.",
            "cost_deterministic": summarise(record["cost_deterministic"]),
            "cost_sample_min": summarise(record["cost_min"]),
            "cost_sample_p50": summarise(record["cost_p50"]),
            "cost_nominal_out": summarise(record["cost_nominal_out"]),
            "rank_of_deterministic_among_K_samples": summarise(
                [float(v) for v in record["rank_of_deterministic"]]
            ),
            "n_steps_deterministic_beats_sample_min": int(n_beats),
            "n_steps": n_steps,
            "frac_steps_deterministic_beats_sample_min": n_beats / n_steps,
            "closest_approach_in_planner_model_m": {
                "deterministic": summarise(record["closest_deterministic_m"]),
                "sample_argmin": summarise(record["closest_argmin_m"]),
                "weighted_average_nominal": summarise(record["closest_nominal_out_m"]),
            },
            "reading": (
                "deterministic cost BELOW the sample minimum at a step means the cost ranks reaching "
                "correctly there and the sampler simply did not draw it — the failure is in the search "
                "distribution, i.e. in the optimizer. Deterministic cost ABOVE the sample minimum means "
                "the cost prefers something other than reaching — the failure is NOT in the optimizer."
            ),
        },
        "N2_collision_attribution": {
            "question": "item E records a 0.754 collision cost share on an OBSTACLE-FREE scene; where "
                        "does the charge come from?",
            "predicate": "cost.collision_mask:279-284 — the SAME object the rollout charges C_crash with "
                         "and the same predicate src.common.outcomes.step_outcomes resolves outcomes "
                         "with (smoke.json check (d), agreement 1.0)",
            "frac_samples_charged": summarise([b["frac_samples_charged"] for b in bands]),
            "frac_samples_charged_by_obstacle_leg": summarise(
                [b["frac_samples_charged_by_obstacle_leg"] for b in bands]
            ),
            "first_charge_horizon_index_p50": summarise(
                [b["first_charge_horizon_index_p50"] for b in bands if b["first_charge_horizon_index_p50"] >= 0]
            ),
            "sample_max_abs_z_p50_m": summarise([b["max_abs_z_p50_m"] for b in bands]),
            "sample_max_abs_z_p95_m": summarise([b["max_abs_z_p95_m"] for b in bands]),
            "sample_max_abs_z_max_m": summarise([b["max_abs_z_max_m"] for b in bands]),
        },
        "N3_delegation_error_closed_loop": {
            "question": "the planner's model assumes the commanded rate IS the realised rate "
                        "(cascade_rate.py:202,612). On the states the closed loop actually visits, how "
                        "far is the plant's body rate from the executed rate command?",
            "rate_command_norm_rad_s": summarise(record["rate_cmd_norm"]),
            "plant_body_rate_norm_rad_s": summarise(record["rate_plant_norm"]),
            "tracking_error_norm_rad_s": summarise(record["rate_tracking_err"]),
        },
        "R0_quantity_3_ess": summarise(record["ess"]),
        "R0_quantity_lambda": summarise(record["lam"]),
        "per_step": {
            "distance_m": record["distance_m"],
            "cost_deterministic": record["cost_deterministic"],
            "cost_min": record["cost_min"],
            "rank_of_deterministic": record["rank_of_deterministic"],
            "ess": record["ess"],
            "abs_z_m": record["abs_z_m"],
            "frac_samples_charged": [b["frac_samples_charged"] for b in bands],
        },
    }


def cited_from_parity() -> dict[str, Any]:
    """R0 quantities 2-6 as the parity artifact already recorded them. CITED, not recomputed."""
    out: dict[str, Any] = {"source_files": [], "leg": "ours_shipped_ou_relative"}
    for path in PARITY_ARTIFACTS:
        payload = json.loads(path.read_text(encoding="utf-8"))
        leg = payload["item_E"]["legs"]["ours_shipped_ou_relative"]
        out["source_files"].append(str(path.relative_to(REPO)))
        out[path.stem] = {
            "closest_approach_m": leg["closest_approach_m"],
            "reaches_position_radius": leg["reaches_position_radius"],
            "quantity_2_exponent_spread_p50": leg["exponent_spread_p50"],
            "quantity_2_exponent_spread_max": leg["exponent_spread_max"],
            "quantity_2_exponent_frac_gt_745": leg["exponent_frac_gt_745"],
            "quantity_3_ess": leg["ess"],
            "quantity_4_nominal_increment_norm": leg["nominal_increment_norm"],
            "quantity_4_nominal_minus_hover_norm": leg["nominal_minus_hover_norm"],
            "quantity_4_shift_consistency_max_abs": leg["shift_consistency_max_abs"],
            "quantity_5_cost_shares_episode": leg["cost_shares_episode"],
            "quantity_5_cost_shares_per_step_p50": leg["cost_shares_per_step_p50"],
            "quantity_6_argmin_rollout_closest_approach_m": leg["argmin_rollout_closest_approach_m"],
            "quantity_6_weighted_average_rollout_closest_approach_m":
                leg["weighted_average_rollout_closest_approach_m"],
            "lam_used": leg["lam_used"],
        }
    out["quantity_1_min_cost_baseline"] = {
        "subtracted": True,
        "site": MIN_COST_BASELINE_SITE,
        "expression": "shifted = cost - cost.min(dim=1, keepdim=True).values",
        "reference_does_the_same_at": "pytorch_mppi/mppi.py:255",
        "note": "a CODE fact, not a measurement; no run is taken for it",
    }
    return out


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--threads", type=int, default=8)
    parser.add_argument("--tag", type=str, default="")
    args = parser.parse_args()

    torch.set_num_threads(int(args.threads))
    t0 = time.time()
    mppi_config = load_mppi_config()
    config = effective_config(mppi_config)
    n_samples = int(mppi_config["cascaded"]["smoke"]["straight_line"]["mppi_n_samples"][0])
    suffix = f"__{args.tag}" if args.tag else ""

    before = dir_state()
    report: dict[str, Any] = {
        "what": "v2.8.4 R0 — the reach diagnosis for the (T, omega_des) cascade",
        "version": __version__,
        "subject": "src/frameworks/mppi/cascade_rate.py. cascade.py (the v5 a_des plan) is NOT the "
                   "subject and is not imported.",
        "variant": "cascaded_rate",
        "process": proc_state(),
        "device": "cpu", "dtype": "torch.float64",
        "torch_threads": int(args.threads),
        "readonly_before": before,
        "no_selection": "MEASUREMENT ONLY. No pool, no cell selection, no ledger row, no promotion, no "
                        "final score. Cascaded, rotor-direct and reference numbers never share a table "
                        "without a variant column.",
        "cited_from_parity": cited_from_parity(),
    }
    report["r0"] = r0_episode(mppi_config, config, n_samples=n_samples)
    report["readonly_after"] = dir_state()
    report["readonly_unchanged"] = report["readonly_before"] == report["readonly_after"]
    report["wall_s"] = round(time.time() - t0, 2)
    write_report(f"r0_diagnosis{suffix}.json", report)
    print(f"readonly unchanged: {report['readonly_unchanged']}", flush=True)
    return 0


if __name__ == "__main__":                                                   # pragma: no cover
    raise SystemExit(main())
