"""v2.8.4 — the reach LADDER for the (T, omega_des) cascade. One flag per rung, every OFF state
bit-parity with the shipped implementation.

SUBJECT. `src/frameworks/mppi/cascade_rate.py`. That file is NOT MODIFIED BY THIS WORK — every rung lives
in the subclass below, so "existing default behaviour unchanged" is structural rather than asserted.
`cascade.py` (the v5 a_des plan) is not the subject and is not imported.

WHAT IS NOT TOUCHED, ANYWHERE IN THIS MODULE
--------------------------------------------
  * the interface: the planner samples v = [T, w_x, w_y, w_z] and nothing else;
  * the inner rate loop `tau = J k_rate (omega_des - omega)` — `RateCascadeController.inner_loop`, CALLED;
  * the post-allocation per-rotor clip — inside `MPPIController.allocate`, CALLED;
  * the full RK4 rotor-thrust SIMULATION plant — `src.common.rk4.rk4_step` on `system`, CALLED;
  * the collision predicate `cost.collision_mask` and the cost's collision term `C_crash * 1{collided}`;
  * the min-cost baseline subtraction, the ESS definition, the degenerate rule, the control hold, the
    receding-horizon shift, the hover centring and the OU sampler.

There is NO reference trajectory, NO global planner and NO map in this file. The one asymmetry any rung
receives is named at its point of use (see R2).

THE OFF-STATE GUARANTEE
-----------------------
`ReachCascadeController.act` dispatches to `super().act` — the shipped `RateCascadeController.act` — the
instant `ReachFlags.any_on` is false. No rung branch is entered, no extra draw is taken from the
generator and no tensor is formed, so the OFF state is the shipped code path itself, not a copy of it.
The parity is nevertheless MEASURED (see `reach_ladder.py`, the `all_flags_off` rung) rather than left as
an argument.

THE RUNGS
---------
R1  `r1_lambda`      the relative-lambda rule's spread estimator. Shipped: `lam * cost.std()` over the K
                     sample costs (`cascade_rate.py:699-702`). R0 measured that std to be dominated by a
                     ~3 % tail of samples charged C_crash for leaving the vertical band, which is why the
                     shipped rule resolves lambda p50 467 and ESS p50 847. "quantile" replaces the
                     estimator by the spread of the SHIFTED cost below a quantile,
                     `lam * (quantile_q(C) - min_k C)`, which the C_crash tail cannot move. The min-cost
                     baseline is unchanged — it is already subtracted at `cascade_rate.py:692`.

R2  `r2_n_seed`      GMPPI's seeded deterministic rollouts (arXiv:2510.12924; the mission's R2, which
                     states the construction: "K_seed of K rollouts generated by the deployed
                     deterministic cascade with per-rollout perturbed gains, the rest sampled as now").
                     The first `r2_n_seed` rows of the sample block are replaced by (T, omega) sequences
                     produced by rolling `smoke_cascade_rate.shipped_pd_command` forward IN THE PLANNER'S
                     OWN MODEL, with per-rollout multiplicative jitter on the three gains it reads off the
                     system object. Row 0 carries the UNJITTERED deployed law. Everything downstream is
                     unchanged: the same cost scores them, the same weights combine them, and because
                     `update = plan + sum_k w_k (sampled_k - base)` the updated nominal is exactly the
                     weighted average of the sampled sequences — which is the form GMPPI's Eq. 3 uses.

                     ASYMMETRY, NAMED AT THE POINT OF USE: the deterministic law reads the GOAL and the
                     STATE only (`a_des = -kp_pos (p - g) - kd_pos v`, all gains read off the system
                     object). It is a feedback law, not a reference trajectory, not a global plan and not
                     a map, and it is available to the baseline for the same reason the goal is.

R3  `r3_yaw`         the yaw channel is not sampled. "damped" sets w_z of every sampled sequence to
                     `-k_yaw * yaw(q)` — a proportional law on the vehicle's OWN yaw, read from the state
                     through the shipped quaternion-to-rotation map, with no reference of any kind — so
                     the sampling space loses one dimension.

R4  `r4_edge`        rollout-index-dependent noise. The drawn perturbation is scaled along the horizon
                     by `edge + (1 - edge) * sin(pi (j + 1/2) / H)`: smaller at the start and the end of
                     the rollout, larger in the middle. `edge = 1.0` is the uniform shipped profile, i.e.
                     OFF.

R5                   NOT IMPLEMENTED. A graded obstacle cost scaled by (N - j) in place of the binary
                     indicator is a change to THE COST'S COLLISION TERM, which the mission puts behind a
                     stop-and-ask. See `docs/versions/v2.8.4/mppi_reach.md`.

R6  `r6_dt_growth`   dynamic rollout timesteps: physical step j of the rollout is integrated for
                     `dt_j = dt * g^j`, renormalised so `sum_j dt_j == H * dt` exactly, so the horizon
                     covers more distance at the same step count without lengthening it in time-integral
                     terms. `g = 1.0` is the uniform shipped schedule, i.e. OFF. The SIMULATION plant's
                     step is untouched — this is the planner's rollout only.

Every constant is read from the system object or the config. Nothing is typed.
"""
from __future__ import annotations

import math
from dataclasses import dataclass
from typing import Any, Mapping

import numpy as np
import torch

from src.common.rk4 import rk4_step
from src.common.system import System
from src.envs.quadrotor_3d import _quat_to_R, _rot
from src.frameworks.mppi.cascade_rate import RateCascadeController, _W
from src.frameworks.mppi.cost import collision_mask, stage_cost, terminal_cost


Tensor = torch.Tensor

R1_MODES = ("off", "quantile")
R3_MODES = ("off", "damped")


@dataclass(frozen=True)
class ReachFlags:
    """One field per rung. The all-default instance is the shipped implementation and `any_on` is False,
    which is what makes the OFF state the shipped code path rather than a re-derivation of it."""

    r1_lambda: str = "off"
    r1_q: float = 0.5
    r2_n_seed: int = 0
    r2_gain_jitter: float = 0.0
    r3_yaw: str = "off"
    r3_k_yaw: float = 0.0
    r4_edge: float = 1.0
    r6_dt_growth: float = 1.0

    def __post_init__(self) -> None:
        if self.r1_lambda not in R1_MODES:
            raise ValueError(f"r1_lambda must be one of {R1_MODES}, got {self.r1_lambda!r}.")
        if self.r3_yaw not in R3_MODES:
            raise ValueError(f"r3_yaw must be one of {R3_MODES}, got {self.r3_yaw!r}.")
        if not 0.0 < self.r1_q <= 1.0:
            raise ValueError(f"r1_q must lie in (0, 1], got {self.r1_q!r}.")
        if self.r2_n_seed < 0:
            raise ValueError(f"r2_n_seed must be >= 0, got {self.r2_n_seed!r}.")
        if not 0.0 <= self.r4_edge <= 1.0:
            raise ValueError(f"r4_edge must lie in [0, 1], got {self.r4_edge!r}.")
        if self.r6_dt_growth <= 0.0:
            raise ValueError(f"r6_dt_growth must be > 0, got {self.r6_dt_growth!r}.")

    @property
    def any_on(self) -> bool:
        return bool(
            self.r1_lambda != "off"
            or self.r2_n_seed > 0
            or self.r3_yaw != "off"
            or self.r4_edge != 1.0
            or self.r6_dt_growth != 1.0
        )

    def record(self) -> dict[str, Any]:
        return {
            "r1_lambda": self.r1_lambda, "r1_q": self.r1_q,
            "r2_n_seed": self.r2_n_seed, "r2_gain_jitter": self.r2_gain_jitter,
            "r3_yaw": self.r3_yaw, "r3_k_yaw": self.r3_k_yaw,
            "r4_edge": self.r4_edge,
            "r6_dt_growth": self.r6_dt_growth,
            "any_on": self.any_on,
            "off_state": "with any_on False, act() dispatches to RateCascadeController.act — the shipped "
                         "code path itself, not a copy",
        }


def yaw_of(x: Tensor) -> Tensor:
    """The vehicle's own yaw, read from the state through the shipped quaternion-to-rotation map
    (`src.envs.quadrotor_3d._quat_to_R`). NO reference of any kind enters: this is the attitude the
    vehicle already has, expressed as the heading of its body x-axis in the world frame."""
    R = _quat_to_R(x[:, 3:7])
    return torch.atan2(R[:, 1, 0], R[:, 0, 0])


class ReachCascadeController(RateCascadeController):
    """The (T, omega_des) cascade with the reach ladder's rungs behind flags.

    `RateCascadeController` is SUBCLASSED, never edited: with every flag at its default this class's
    `act` is `RateCascadeController.act`, reached through `super()`, so the shipped behaviour is the
    shipped code and not a reproduction of it.
    """

    def __init__(self, *args: Any, flags: ReachFlags | None = None, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self.flags = flags if flags is not None else ReachFlags()
        # R4's horizon profile, mean-normalised so the rung moves the SHAPE of the perturbation along the
        # rollout and not its overall size. Built once; `edge == 1` makes it identically one.
        horizon = int(self.params.horizon)
        j = torch.arange(horizon, device=self.device, dtype=self.dtype)
        shape = self.flags.r4_edge + (1.0 - self.flags.r4_edge) * torch.sin(
            math.pi * (j + 0.5) / float(horizon)
        )
        self.r4_profile = (shape / shape.mean()).view(1, 1, horizon, 1)
        # R6's per-physical-step integration times, renormalised so the horizon's total time is exactly
        # the shipped `H * control_hold * dt`. `growth == 1` makes every entry `dt`.
        steps = horizon * int(self.control_hold)
        k = torch.arange(steps, device=self.device, dtype=self.dtype)
        raw = torch.pow(torch.as_tensor(float(self.flags.r6_dt_growth), dtype=self.dtype), k)
        self.r6_dt = (raw / raw.sum() * (steps * self.dt)).tolist()
        # R2's per-rollout gain jitter is drawn ONCE, from a DEDICATED generator, so that switching R2 on
        # does not shift the OU perturbation stream: the rung is then isolated from the RNG and the two
        # legs differ only by the seeded rows. Row 0 is exactly the unjittered deployed law.
        self.r2_factor: Tensor | None = None
        if self.flags.r2_n_seed > 0:
            gen = torch.Generator(device="cpu").manual_seed(int(self.params.seed))
            z = torch.randn((int(self.flags.r2_n_seed), 3), generator=gen, dtype=torch.float64)
            factor = torch.exp(float(self.flags.r2_gain_jitter) * z)
            factor[0] = 1.0
            self.r2_factor = factor.to(device=self.device, dtype=self.dtype)
        self.seed_gain_record: dict[str, Any] | None = None
        # R2 HONESTY DIAGNOSTICS. How much of the weight mass the seeded rows carry, and whether the
        # minimum-cost sample is one of them, per decision step. Without these the rung could not be
        # told apart from running the deterministic law directly, which is the thing it must not become.
        self.seed_weight_mass: list[float] = []
        self.seed_is_argmin: list[bool] = []

    # ---- the record a cell / smoke JSON carries ---------------------------------------------------
    def reach_record(self) -> dict[str, Any]:
        record = {
            "what": "the v2.8.4 reach ladder — one flag per rung, every OFF state the shipped code path",
            "subject_file_modified": False,
            "subject": "src/frameworks/mppi/cascade_rate.py (subclassed, not edited)",
            "flags": self.flags.record(),
            "unchanged": [
                "the (T, omega) interface", "the inner rate loop", "the post-allocation per-rotor clip",
                "the full RK4 rotor-thrust simulation plant", "the collision predicate",
                "the cost's collision term C_crash * 1{collided}",
                "the min-cost baseline subtraction (cascade_rate.py:692)",
                "the ESS definition, the degenerate rule, the control hold, the receding-horizon shift",
                "hover centring and the OU sampler",
            ],
            "no_action_perturbation_term": (
                "the action-perturbation / control-cost term is NOT added. Settled by the parity work and "
                "explicitly excluded by the mission; GMPPI (arXiv:2510.12924, Eq. 3) weights from "
                "trajectory cost alone with a min-cost baseline and carries no such term."
            ),
            "r6_dt_schedule_s": self.r6_dt if self.flags.r6_dt_growth != 1.0 else "uniform (dt)",
        }
        if self.seed_gain_record is not None:
            record["r2_seed_gains"] = self.seed_gain_record
        return record

    # ---- R2: the seeded deterministic rollouts ---------------------------------------------------
    @torch.no_grad()
    def seeded_sequences(self, x: Tensor, goal: Tensor, n_seed: int) -> Tensor:
        """`n_seed` (T, omega_des) sequences produced by the DEPLOYED deterministic cascade with
        per-rollout perturbed gains, rolled forward in the PLANNER'S OWN model. Returns [n_seed, H, 4].

        The law is `smoke_cascade_rate.shipped_pd_command` written batched over the gain axis — the same
        expression, which `data/runs/v2.8.4/mppi_cascaded/smoke.json` check (f) records reproducing
        `system.lqr_action` to 0.0 N. All four gains (kp_pos, kd_pos, kp_att, kd_att), the mass and the
        gravity are READ OFF THE SYSTEM OBJECT; nothing is typed.

        The rate limit and the low-pass are the planner's own (`cascade_rate.py:328-334` and `:610`), so
        what comes back is an admissible plan in exactly the space the sampler searches.

        ASYMMETRY, NAMED HERE: the law reads the GOAL and the STATE. No reference trajectory, no global
        planner, no map.

        `x` is [1, state_dim] and `goal` is [1, 3] — the ladder's smoke runs one scene, and the seeded
        rung is only ever built for a single scene row.
        """
        system = self.system
        horizon = int(self.params.horizon)
        jitter = float(self.flags.r2_gain_jitter)
        assert self.r2_factor is not None
        factor = self.r2_factor[:n_seed]
        kp_pos = float(system.kp_pos) * factor[:, 0:1]
        kd_pos = float(system.kd_pos) * factor[:, 1:2]
        ratio = (float(system.kp_att) / float(system.kd_att)) * factor[:, 2:3]
        self.seed_gain_record = {
            "n_seed": int(n_seed),
            "jitter_log_std": jitter,
            "row_0_is_unjittered_deployed_law": True,
            "gains_read_from_system": {
                "kp_pos": float(system.kp_pos), "kd_pos": float(system.kd_pos),
                "kp_att": float(system.kp_att), "kd_att": float(system.kd_att),
            },
            "factor_min": float(factor.min().item()), "factor_max": float(factor.max().item()),
            "asymmetry": "the deterministic law reads the GOAL and the STATE only; no reference "
                         "trajectory, no global planner, no map",
        }

        beta = self.lowpass_beta
        state = x.expand(n_seed, -1).clone()
        goal_rows = goal.expand(n_seed, -1)
        rate_f = state[:, _W].clone()
        gravity = torch.zeros(n_seed, 3, device=self.device, dtype=self.dtype)
        gravity[:, 2] = float(system.gravity)
        entries = []
        for k in range(horizon):
            p = system.position(state)
            v = state[:, 7:10]
            a_des = -kp_pos * (p - goal_rows) - kd_pos * v
            f_des = float(system.mass) * (a_des + gravity)
            R = _quat_to_R(state[:, 3:7])
            b3 = R[:, :, 2]
            thrust = (f_des * b3).sum(dim=1).clamp(min=0.0).unsqueeze(-1)
            b3_des = f_des / torch.clamp(torch.linalg.norm(f_des, dim=1, keepdim=True), min=1e-9)
            e_att_body = _rot(R.transpose(1, 2), torch.cross(b3, b3_des, dim=1))
            omega_des = ratio * e_att_body
            command = self.rate_limit(torch.cat([thrust, omega_des], dim=-1))
            entries.append(command.clone())
            rate_f = beta * rate_f + (1.0 - beta) * command[:, 1:]
            state = torch.cat([state[:, :10], rate_f], dim=1)
            state = rk4_step(self.planner, state, command, self.dt)
            del k
        return torch.stack(entries, dim=1)                                  # [n_seed, H, 4]

    # ---- R6: the rollout with a non-uniform integration schedule ---------------------------------
    @torch.no_grad()
    def _rollout_chunk(
        self,
        x: Tensor,
        sampled: Tensor,
        goal: Tensor,
        centers: Tensor,
        radii: Tensor,
        active: Tensor,
    ) -> tuple[Tensor, Tensor]:
        """`RateCascadeController._rollout_chunk` with the per-step integration time taken from R6's
        schedule. With `r6_dt_growth == 1.0` every entry of that schedule is `self.dt`, so this reduces to
        the parent — and the parent is CALLED directly in that case, so the OFF path is the shipped one.

        The freeze-on-collision rule, the charged-once C_crash, the SAME `collision_mask`, the SAME
        `stage_cost` with `x_prev`, the SAME `terminal_cost` and the endpoint probe are unchanged.
        """
        if self.flags.r6_dt_growth == 1.0:
            return super()._rollout_chunk(x, sampled, goal, centers, radii, active)
        batch, n, horizon, plan_dim = sampled.shape
        flat = batch * n
        state = x.unsqueeze(1).expand(batch, n, -1).reshape(flat, -1)
        goal_flat = goal.unsqueeze(1).expand(batch, n, -1).reshape(flat, -1)
        cost = torch.zeros(flat, device=self.device, dtype=self.dtype)
        dead = torch.zeros(flat, dtype=torch.bool, device=self.device)
        beta = self.lowpass_beta
        rate_f = state[:, _W].clone()
        for k in range(horizon * self.control_hold):
            command = self.held_control(sampled, k).reshape(flat, plan_dim)
            rate_f = beta * rate_f + (1.0 - beta) * command[:, 1:]
            state = torch.cat([state[:, :10], rate_f], dim=1)
            nxt = rk4_step(self.planner, state, command, self.r6_dt[k])     # R6: the schedule's step
            previous = state
            state = torch.where(dead.unsqueeze(-1), state, nxt)
            collided = collision_mask(
                self.system.position(state).view(batch, n, -1), centers, radii, active, self.cost
            ).reshape(flat)
            newly = collided & ~dead
            cost = cost + newly.to(self.dtype) * self.cost.c_crash
            dead = dead | collided
            cost = cost + stage_cost(
                self.system, state, goal_flat, self.cost, self.recovery, x_prev=previous
            )
        cost = cost + terminal_cost(self.system, state, goal_flat, self.cost)
        if self.endpoint_probe:
            with torch.random.fork_rng(devices=self._fork_devices):
                self._endpoint_chunk_dists.append(
                    torch.linalg.norm(self.system.position(state) - goal_flat, dim=-1).view(batch, n)
                )
        return cost.view(batch, n), dead.view(batch, n)

    # ---- one control step -------------------------------------------------------------------------
    @torch.no_grad()
    def act(self, x: Tensor, scene: Any) -> Tensor:
        """`RateCascadeController.act` with the rung hooks. With every flag off the shipped method is
        called through `super()` and NOTHING below runs — no branch, no draw, no allocation."""
        if not self.flags.any_on:
            return super().act(x, scene)

        from src.common.observation import scene_goal_tensor
        from src.frameworks.mppi.recovery import tilt_cos, tilt_deg_from_cos

        batch = int(x.shape[0])
        if self.plan is None or self.plan.shape[0] != batch:
            self.reset(batch)
        assert self.plan is not None and self.degenerate_steps is not None

        if self.steps_since_reset % self.control_hold != 0:
            assert self.last_action is not None
            self.last_decision = False
            self.steps_since_reset += 1
            if self.endpoint_probe:
                self._endpoint_current.append(np.full(batch, np.nan, dtype=np.float32))
            return self.last_action.clone()

        x = x.to(device=self.device, dtype=self.dtype)
        centers, radii, active = self._scene_tensors(scene)
        goal = scene_goal_tensor(scene, x)                                   # [B,3]

        if self.steps_since_reset == 0:
            self.spawn_tilt_deg = tilt_deg_from_cos(tilt_cos(self.system, x))

        base = self.absolute(self.plan)                                      # [B,H,4]
        noise = self._draw_noise(batch)                                      # [B,N,H,4] OU, inherited
        if self.flags.r4_edge != 1.0:
            noise = noise * self.r4_profile                                  # R4
        raw = base.unsqueeze(1) + noise
        if self.flags.r3_yaw == "damped":                                    # R3
            yaw_cmd = (-float(self.flags.r3_k_yaw) * yaw_of(x)).view(batch, 1, 1, 1)
            raw = torch.cat([raw[..., :3], yaw_cmd.expand_as(raw[..., 3:])], dim=-1)
        sampled = self.rate_limit(raw)
        n_seed = min(int(self.flags.r2_n_seed), int(self.params.n_samples))
        if n_seed > 0:                                                       # R2
            if batch != 1:
                raise NotImplementedError(
                    "the seeded-rollout rung is built for the ladder's single-scene smoke; it has not "
                    f"been generalised to a scene batch (got batch = {batch})."
                )
            sampled[:, :n_seed] = self.seeded_sequences(x, goal, n_seed).unsqueeze(0)
        with torch.random.fork_rng(devices=self._fork_devices):
            self.rate_limit_entries += int(raw[..., 1:].numel())
            self.rate_limit_clamped += int((raw[..., 1:] != sampled[..., 1:]).sum().item())
        effective_noise = sampled - base.unsqueeze(1)
        del raw, noise
        cost, all_collided = self._rollout_cost(x, sampled, goal, centers, radii, active)
        del sampled

        if self.endpoint_probe:
            with torch.random.fork_rng(devices=self._fork_devices):
                assert self.last_endpoint_dist is not None
                self.last_best_endpoint_dist = self.last_endpoint_dist.gather(
                    1, cost.argmin(dim=1, keepdim=True)
                ).squeeze(1)
                self._endpoint_current.append(
                    self.last_best_endpoint_dist.detach().to(torch.float32).cpu().numpy().copy()
                )

        # THE MIN-COST BASELINE, unchanged (cascade_rate.py:692)
        shifted = cost - cost.min(dim=1, keepdim=True).values
        if self.params.lam_mode == "absolute":
            lam_eff: Any = self.params.lam
            lam_eff_row = torch.full(
                (batch,), float(self.params.lam), device=self.device, dtype=self.dtype
            )
        elif self.flags.r1_lambda == "quantile":                             # R1
            spread = torch.quantile(shifted, float(self.flags.r1_q), dim=1, keepdim=True)
            lam_eff = torch.clamp(
                float(self.params.lam) * spread, min=float(self.params.lam_eps_abs)
            )
            lam_eff_row = lam_eff.squeeze(1)
        else:
            lam_eff = torch.clamp(
                float(self.params.lam) * cost.std(dim=1, keepdim=True),
                min=float(self.params.lam_eps_abs),
            )
            lam_eff_row = lam_eff.squeeze(1)
        weight = torch.exp(-shifted / lam_eff)
        partition = weight.sum(dim=1, keepdim=True)
        degenerate = all_collided | ~torch.isfinite(partition).squeeze(1) | (partition.squeeze(1) <= 0.0)
        weight = weight / torch.clamp(partition, min=torch.finfo(self.dtype).tiny)
        ess = 1.0 / torch.clamp(weight.square().sum(dim=1), min=torch.finfo(self.dtype).tiny)

        if n_seed > 0:
            with torch.random.fork_rng(devices=self._fork_devices):
                self.seed_weight_mass.append(float(weight[0, :n_seed].sum().item()))
                self.seed_is_argmin.append(bool(int(cost[0].argmin().item()) < n_seed))

        update = self.plan + (weight.unsqueeze(-1).unsqueeze(-1) * effective_noise).sum(dim=1)
        del effective_noise
        plan = torch.where(degenerate.view(-1, 1, 1), self.plan, update)

        head = self.rate_limit(self.absolute(plan[:, 0]))
        rate_applied = self.lowpass_beta * x[:, _W] + (1.0 - self.lowpass_beta) * head[:, 1:]
        command = torch.cat([head[:, :1], rate_applied], dim=-1)
        action = self.inner_loop(x, command, count=True)                     # box-clipped, unchanged
        self.plan = self._shift(plan)
        self.last_degenerate = degenerate
        self.last_ess = ess
        self.last_ess_pre = ess
        self.last_lam_eff_pre = lam_eff_row
        self.last_b3_event = torch.zeros(batch, dtype=torch.bool, device=self.device)
        self.last_lam_eff = lam_eff_row
        self.last_action = action
        self.last_decision = True
        self.steps_since_reset += 1
        self.degenerate_steps = self.degenerate_steps + degenerate.long()
        assert self.b3_events is not None
        return action


def build_reach_controller(
    mppi_config: Mapping[str, Any],
    config: Mapping[str, Any],
    *,
    flags: ReachFlags,
    n_samples: int,
    noise: str,
    lam_mode: str,
    device: torch.device,
    dtype: torch.dtype,
) -> tuple[System, ReachCascadeController]:
    """Construct the ladder's controller directly, mirroring `evaluate_mppi.build_framework`'s own
    `rate_cascade` branch (`evaluate_mppi.py:141-152`) entry for entry, so that NO existing file has to be
    edited to reach the subclass. The base configuration is `mppi.v5.base_cell`, read through
    `stages_v5.base_kwargs`, and the cascade mapping is `screen_cascaded.cascade_kwargs` — the same two
    the parity harness's `build` uses."""
    from src.frameworks.jt_pncbf.train import make_system      # evaluate_mppi.py:57's own import
    from src.frameworks.mppi.cost import CostParams
    from src.frameworks.mppi.mppi_controller import MPPIParams
    from src.frameworks.mppi.recovery import RecoveryParams
    from src.frameworks.mppi.screen_cascaded import cascade_kwargs
    from src.frameworks.mppi.stages_v5 import base_kwargs

    smoke_cfg = mppi_config["cascaded"]["smoke"]
    kwargs = base_kwargs(mppi_config)
    kwargs["horizon"] = int(smoke_cfg["straight_line"]["mppi_horizon"])
    kwargs["noise"] = str(noise)
    kwargs["lam_mode"] = str(lam_mode)

    system = make_system(config)
    params = MPPIParams.from_config(
        mppi_config, n_samples=int(n_samples), horizon=kwargs["horizon"], lam=kwargs["lam"],
        sigma=kwargs["sigma"], seed=int(mppi_config["cascaded"]["scale"]["seed"]), sample_chunk=0,
        space=kwargs["space"], noise=kwargs["noise"], lam_mode=kwargs["lam_mode"],
        center=kwargs["center"], control_hold=kwargs["control_hold"],
    )
    cost_params = CostParams.from_config(
        mppi_config, config["env"], c_crash=kwargs["c_crash"], terminal=kwargs["terminal"],
        g1=kwargs["g1"], g2=kwargs["g2"], g3=kwargs["g3"], g4=kwargs["g4"],
    )
    recovery = RecoveryParams.from_config(
        mppi_config, b1=kwargs["b1"], b2=kwargs["b2"], b3=kwargs["b3"]
    )
    controller = ReachCascadeController(
        system, config, params, cost_params, device=device, dtype=dtype, recovery=recovery,
        cascade=cascade_kwargs(mppi_config, float(smoke_cfg["rate_gain_factor"])),
        flags=flags,
    )
    return system, controller
