"""Hand-authored verdict cells for the 400-character cap.

Slot order per row: 1 what the row is | 2 headline result | 3 comparability | 4 bold, promotion,
supersession | 5 pointer (detail path plus companion anchor). A slot that does not apply is
omitted, never padded. Register is normative: no narrative, no rationale. Numbers appear only where
the headline slot needs one, and every number here also occurs in that row's pre-cap text -- checked
mechanically by ledger_length_apply.measurement_numbers before anything is written.

`{A}` is replaced with the row's companion anchor.
"""
from __future__ import annotations

V: dict[int, str] = {
 62: "DI SOTA 0.8698, 3-seed mean; CI overlaps the prior 0.8568, so a point estimate and not a CI-confirmed beat. NOT RANKABLE under cps_v2, which reads '-'. SUPERSEDED at the v2.9.1 close; bold moved to L314, content kept. v2.3.0_results.md; docs/ledger_verdicts.md#{A}.",
 64: "EXPERIMENT: one global actuator change, u_max 2 -> 20. cps 0.9419 against the v2.3.0 baseline's 0.8700. NOT comparable to any +/-2 row and not +/-2-deployable; single seed. SOTA UNCHANGED, no bold change. docs/versions/v2.3.0_results.md; docs/ledger_verdicts.md#{A}.",
 80: "Friction condition at D-slow, dual-reported legacy 0.5893 / cps_v2 0.8327. P-F3 CONFIRMED but P-F1, P-F2 and P-F4 REFUTED: friction did NOT reduce intervention. Dual-scored across the definition boundary, so not comparable across it. NOT SOTA. docs/ledger_verdicts.md#{A}.",
 81: "Training-free reach-witness follower, no learned object. Coverage gate PASSED at 0.98; rescue and cost REFUTED. Not comparable to any filtered row -- cps == cps_v2 only because there are no filter steps. NOT SOTA-comparable, no bold change. reach_witness.md; docs/ledger_verdicts.md#{A}.",
 82: "ARM-C: the v2.3.0 learned-V filter re-evaluated at the D-fast deploy axis. GATE PASS; D-fast REGRESSES it by -0.0072 cps_v2 while V_M GAINS +0.0031, so the gain is V_M-SPECIFIC. Changed deploy axis, not comparable to D-slow rows. NOT a SOTA claim. close_prep_batch.md; docs/ledger_verdicts.md#{A}.",
 87: "CPI iteration-3: policy pi_3 under the frozen certificate V_hat_2. cps_v2 0.660 REGRESSED against iteration-2's 0.721; P-PI2 failed and monotonicity halted. LINE REJECTED, so a terminal record and not a comparator. No bold change. phase_i1_loop_report.md; docs/ledger_verdicts.md#{A}.",
 108: "J-arc arm B: the S' shield over the learned filter. P-J1 and P-J2 PASS, the shield transferring at no cps cost; P-J4 FALSIFIED. Different deployment class, so not comparable to unshielded rows. NOT SOTA-bold; flag Researcher. phase_j_report.md; docs/ledger_verdicts.md#{A}.",
 112: "J-arc arm B': the arm-B shield at about twice the checks per episode. P-J3 PASS, cps_v2 0.9174 on arm B's 0.9171, so the ladder buys no cps. Different deployment class, not comparable to unshielded rows. NOT SOTA-bold; flag Researcher. phase_j_report.md; docs/ledger_verdicts.md#{A}.",
 137: "[M6] JT co-trained policy on the pre-per-rotor wrench action box. H1 CONFIRMED, cps 0.9329 CI-separated above the pre-JT 0.8481. NOT comparable to any current-plant result; the checkpoint does not load on it. SUPERSEDED by v2.8.0, RELEASED FROM BOLD, retained for provenance. docs/ledger_verdicts.md#{A}.",
 209: "EXPLORATORY P3 arm comparison at the last common pre-crash checkpoint, matched budget, neither arm resumed. obstacle 0.0095 / floor 0.0335 / ceiling 0.0005. The 50000-step comparison is comparison-unavailable; NOT the dual deliverable. Single seed, unbolded. docs/versions/v2.8.0/p3_common_step.md; docs/ledger_verdicts.md#{A}.",
 231: "LINEAGE BREAK: soft_topk encoder beta=30, terminal 0.30, policy fresh. T2 FAILED at gate reach 0.8620, so the pipeline STOPPED and nothing was secured. NOT SOTA-comparable to the hard-encoder v2.8.0 row, the observation channel having changed. Unbolded. docs/versions/v2.8.1/s1_retrain.md; docs/ledger_verdicts.md#{A}.",
 232: "CONTROL for v2.8.2: the v2.8.0 recipe, hard_topk, terminal 0.30. T2 PASSES at gate reach 0.9205, attributing v2.8.1's failure to the ENCODER not the terminal. NOT comparable to the 3-D bold 0.7919, being neither step- nor terminal-matched. UNBOLDED. docs/versions/v2.8.2/s2_conditions.md; docs/ledger_verdicts.md#{A}.",
 233: "alpha_unsafe axis, CTRL recipe with only alpha_unsafe 100 -> 30. Gate cps 0.7653 and infeas 0.1106 sit on CTRL's, so this rung is INERT on infeasibility. CIs overlap CTRL, so no separation either way; NOT secured. UNBOLDED. docs/versions/v2.8.2/s2_conditions.md; docs/ledger_verdicts.md#{A}.",
 235: "alpha_unsafe axis, CTRL recipe with only alpha_unsafe 100 -> 3. Infeas 0.0802 is the largest reduction on the ladder, but collision RISES to 0.0570 and cps falls below CTRL: the axis TRADES infeasibility for collision. Single seed. UNBOLDED. docs/versions/v2.8.2/s2_conditions.md; docs/ledger_verdicts.md#{A}.",
 236: "FLOOR axis, deployed-fallback co-adaptation, stopped on Researcher decision. CONFOUND BROKEN: at matched fallback the floor gain vanishes, so the E0 pass was the EVAL FALLBACK. STEP-MISMATCHED and not converged, so NOT comparable to CTRL. UNBOLDED. docs/versions/v2.8.2/fb_floor.md; docs/ledger_verdicts.md#{A}.",
 249: "PPO BASELINE, no certificate and no filter, under a registered shaped reward. Near-complete collision avoidance and beats the LQR nominal, but reach ~0 and timeout-dominated. Conditional on that shaping, NOT comparable to the certificate rows on equal terms. UNBOLDED. docs/versions/v2.8.2/ppo_baseline.md; docs/ledger_verdicts.md#{A}.",
 271: "ceiling axis C=1.3, eval-only against CTRL at matched step 24000. Delta cps below D0's 0.0083 floor, so NO cps claim. SUPERSEDED 2026-08-12 by the v2.8.5 exp0.125 step-45000 row; bold released and stays released. docs/versions/v2.8.4/ceiling_axis.md; docs/ledger_verdicts.md#{A}.",
 277: "gamma axis horizon_final 33.0 against the ARM's 100.0. coll_band_lower 0.0165 against 0.0175, a strict subset of the ARM's scene set; cps delta below D0's floor with overlapping CIs. NOT a one-variable contrast, schedule_n_steps differing too. Diagnostic, no bold change. docs/versions/v2.8.4/gamma_axis.md; docs/ledger_verdicts.md#{A}.",
 278: "eval-only ARM comparator on fullscr41, scored beside the gamma row because no ARM number existed there. gamma-minus-ARM carries the same signs as on fullcb. Both cps magnitudes below D0's 0.0083 floor, so no cps claim. Diagnostic, no bold change. docs/versions/v2.8.4/gamma_rescore.md; docs/ledger_verdicts.md#{A}.",
 279: "ITEM 1: the in-loop-vs-final gap decomposed on one checkpoint. The filter cell accounts for -0.0075 and the pool composition for +0.0120, summing to the +0.0045 total. Selection bias is NOT separable, all three scoring the same checkpoint. Diagnostic. docs/versions/v2.8.4/gamma_rescore.md; docs/ledger_verdicts.md#{A}.",
 280: "ITEM 2: second-pool reproduction of the gamma-minus-ARM deltas. All five fields carry the SAME SIGN on both full pools. Both cps magnitudes below D0's 0.0083 floor, so no cps claim on either pool. Diagnostic, no bold change. docs/versions/v2.8.4/gamma_rescore.md; docs/ledger_verdicts.md#{A}.",
 288: "registered-cell row, hazard exp ell 0.175. Series TRUNCATED by a CUDA OOM with no checkpoint beyond round 360, so 0.8520 is the maximum of a truncated series and not comparable to a full-budget row. SUPERSEDED 2026-08-12; promotion withdrawn, bold released. docs/ledger_verdicts.md#{A}.",
 294: "quadrotor_3d SOTA-of-record when written; a 06_workflow 2.5 BASIS classification, NOT a CI-separated beat. Single seed, CI overlapping every comparator, so no separation claimed. Supersedes the exp0.175 and ARM rows; itself SUPERSEDED 2026-08-13, bold released. docs/ledger_verdicts.md#{A}.",
 297: "buffer_cap 2000 against COMPRESS1000's 1000000, one config key. STOPPED BY RESEARCHER INSTRUCTION, so no end-of-run evaluation and an in-loop maximum over 570 rounds. NOT comparable to a 1000-round maximum; buffer_cap was NOT a registered axis and no verdict is drawn. docs/versions/v2.9.0/final_scoring.md; docs/ledger_verdicts.md#{A}.",
 298: "buffer_cap 10000 against COMPRESS1000's 1000000, one config key; ran to its own terminal path. Registered-cell re-score at best_step. buffer_cap was NOT a registered axis of v2.9.0 and NO verdict is drawn on it. Diagnostic, no bold change. docs/versions/v2.9.0/final_scoring.md; docs/ledger_verdicts.md#{A}.",
 299: "the compressed-update condition on the exp0.125 geometry, run to its own terminal path. REGISTERED AXIS A1 FALSIFIED: below its control at 13 of 14 matched rounds, mean paired difference -0.034378; A2 HOLDS. CIs overlap at 13 of 14, so no separation and this row is not a comparison. docs/versions/v2.9.0/final_scoring.md; docs/ledger_verdicts.md#{A}.",
 300: "buffer_cap 5000 against COMPRESS1000's 1000000, one config key; ran to its own terminal path. Registered-cell re-score at best_step. buffer_cap was NOT a registered axis of v2.9.0 and NO verdict is drawn on it. Diagnostic, no bold change. docs/versions/v2.9.0/final_scoring.md; docs/ledger_verdicts.md#{A}.",
 301: "the v2.9.1 scene law, five clearance floors moved together, against BUFCAP10K with the evaluation path untouched. Over 48 matched rounds A1 FALSIFIED, A2 HOLDS, A3 FALSIFIED. No CI separation on any channel; single seed. Diagnostic, no bold change. docs/versions/v2.9.1/final_scoring.md; docs/ledger_verdicts.md#{A}.",
 302: "the sigma-floor condition, sigma_min 0.3 -> 0.0 against SCENELAW_B10K, one config key. Against that control A1 FALSIFIED, A2 HOLDS, A3 HOLDS. That pairing is not one of the two registered, sigma_min was NOT a registered axis, and no verdict is drawn on it. Diagnostic. docs/versions/v2.9.1/final_scoring.md; docs/ledger_verdicts.md#{A}.",
 303: "the v2.9.1 scene law, five clearance floors moved together, against COMPRESS1000 with the evaluation path untouched. Over 48 matched rounds A1 FALSIFIED, A2 HOLDS, A3 HOLDS. No CI separation on any channel; single seed. Diagnostic, no bold change. docs/versions/v2.9.1/final_scoring.md; docs/ledger_verdicts.md#{A}.",
 304: "**quadrotor_3d SOTA-of-record on the registered cell; a 06_workflow 2.5 BASIS classification, NOT a CI-separated beat. Against the superseded exp0.125 row the difference is +0.002098, 0.25x the 0.0083 floor, CIs overlapping and single seed on both, so NO separation either way. BOLD. docs/ledger_verdicts.md#{A}**",
 305: "the v2.9.1 OC arm on quadrotor_3d at its own best_step; a diagnostic baseline for the JT arm warm-started from this checkpoint. Against the unfiltered LQR nominal the certificate ADDS +1.328835. NOT a rank claim, the JT arm holding the record. Nothing bolded or promoted. docs/versions/v2.9.1/oc_arm_rows.md; docs/ledger_verdicts.md#{A}.",
 306: "the v2.9.1 OC arm on quadrotor_planar at its own best_step; a diagnostic baseline for the JT arm warm-started from this checkpoint. Against the unfiltered LQR nominal the certificate ADDS +0.865150. NOT a rank claim; hazard.ell is an UNSCREENED INHERITANCE here. Nothing bolded. docs/ledger_verdicts.md#{A}.",
 307: "the v2.9.1 OC arm on double_integrator at its own best_step; a diagnostic baseline for the JT arm warm-started from this checkpoint. Against the unfiltered LQR nominal the certificate ADDS +0.889959. NOT a rank claim; hazard.ell is an UNSCREENED INHERITANCE here. Nothing bolded. docs/ledger_verdicts.md#{A}.",
 308: "the v2.9.1 OC arm on unicycle at its own best_step; a diagnostic baseline for the JT arm warm-started from this checkpoint. Against the unfiltered LQR nominal the certificate ADDS +0.668486. NOT a rank claim; hazard.ell is an UNSCREENED INHERITANCE here. Nothing bolded. docs/ledger_verdicts.md#{A}.",
 309: "the v2.9.1 JT arm on double_integrator, warm-started value-only from its own OC best.pt. Against its OC row L307 on the same pool and cell, +0.024298. Single seed both sides, NO CI separation claimed either way; hazard.ell is an UNSCREENED INHERITANCE. No bold change, no promotion. docs/ledger_verdicts.md#{A}.",
 310: "the v2.9.1 JT arm on unicycle, warm-started value-only from its own OC best.pt. Against its OC row L308 on the same pool and cell, +0.202640. Single seed both sides, NO CI separation claimed either way; hazard.ell is an UNSCREENED INHERITANCE. No bold change, no promotion. docs/ledger_verdicts.md#{A}.",
 311: "the v2.9.1 JT arm on quadrotor_planar, warm-started value-only from its own OC best.pt and a RELAUNCH of the R3 run that died of CUDA OOM. Against its OC row L306, +0.116590. Single seed, NO CI separation claimed either way. No bold change, no promotion. docs/ledger_verdicts.md#{A}.",
 312: "the v2.9.1 JT arm on quadrotor_3d, warm-started value-only from its own OC best.pt so the column matches the other three. Against L305 +0.186152; against L304 -0.004236, below the 0.0083 floor and inside L304's CI, so NO separation. Table I takes this row, BOLD STAYS AT L304. docs/ledger_verdicts.md#{A}.",
 313: "**CURRENT-BASIS RE-SCORE of the flagged bold L132 on the current cell and pool. RESULT 0.851927 against 0.9036, BELOW the bold by 6.2x the 0.0083 floor. A tighter reach predicate makes it comparable to L306 and L311 but NOT to L132's own figure. BOLD MOVED HERE, superseding L132; a BASIS re-score, not a beat. docs/ledger_verdicts.md#{A}**",
 314: "**CURRENT-BASIS RE-SCORE of the flagged bold L62, whose 3-seed snapshots were located. RESULT 0.868247 against 0.8698, BELOW the bold by 0.19x the 0.0083 floor and inside the seed spread, so NOT a separation. On the regenerated DI pool, comparable to L307 and L309 and NOT to L62. BOLD MOVED HERE, superseding L62. docs/ledger_verdicts.md#{A}**",
 315: "VALUE-ONLY CONTINUATION of L312, policy frozen and value still learning. REGISTERED HYPOTHESIS FALSIFIED on both named columns and in the wrong direction: infeasibility and the EMPTY episode share both ROSE. cps is reported and is NOT the falsifier. No bold change, no promotion. docs/versions/v2.9.1/value_only_continuation.md; docs/ledger_verdicts.md#{A}.",
 316: "v2.9.2 REGISTERED AXIS, OC arm: c_gain 0.3 -> 0.0, one flattened key from L305's own config. A1 HOLDS, coll_obstacle 0.0310 -> 0.0500, the band channels unchanged. cps is reported and NOT claimed, being no registered observable; best_step is the final eval. NOT bold, NOT promoted. docs/versions/v2.9.2/cgain_cells.md; docs/ledger_verdicts.md#{A}.",
 317: "PRIVILEGED MODEL-BASED REFERENCE POINT, NOT A PEER of a learned-certificate row: MPPI reads the full state and exact obstacle field. Reach 0.2980, collision 0.6525. Infeasibility is structurally inapplicable under its identity filter. NOT bold. docs/versions/v2.9.2/mppi_registered.md; docs/ledger_verdicts.md#{A}.",
 318: "v2.9.2 REGISTERED AXIS, JT arm: c_gain 0.3 -> 0.0, with value_init repointed off a c_gain-0.3 certificate. A1 HOLDS, coll_obstacle 0.0075 -> 0.0090, and WITH THE OC ARM ON BOTH. cps reported, NOT claimed; warm-started from a BUDGET-TRUNCATED checkpoint. NOT bold, NOT promoted. docs/versions/v2.9.2/cgain_cells.md; docs/ledger_verdicts.md#{A}.",
 319: "v2.9.2 MISMATCH TEST, L312's policy with L305's certificate. PREDICTION HOLDS: cps 0.6925 against the matched cell's 0.8680, coll_obstacle carrying it. A WRONG CERTIFICATE and NOT A VALID DEPLOYMENT, comparable only to the other mismatch cells. NOT bold, nothing recommended. docs/versions/v2.9.2/decomp.md; docs/ledger_verdicts.md#{A}.",
 320: "v2.9.2 MISMATCH TEST, the shipped LQR nominal with L312's certificate. PREDICTION FALSIFIED: cps 0.8136 against the matched cell's 0.6818, so the mismatched certificate EXCEEDS the matched. A WRONG CERTIFICATE, comparable only to the other mismatch cells. NOT bold. docs/versions/v2.9.2/decomp.md; docs/ledger_verdicts.md#{A}.",
}

_H400 = {321: ("L305", "+0.051139"), 322: ("L306", "+0.037161"), 323: ("L307", "+0.001764"),
         324: ("L308", "+0.004828"), 325: ("L309", "+0.000745"), 326: ("L310", "+0.000085"),
         327: ("L311", "+0.013638"), 328: ("L312", "+0.017325")}
for _ln, (_p, _d) in _H400.items():
    V[_ln] = (f"NEW CELL at eval.max_steps 400, every other key identical to {_p}'s. Against a "
              f"same-instrument 200-step control, per-episode cps difference {_d}, 04_eval 5 "
              f"scene-bootstrap CI. NOT COMPARABLE TO ANY 200-STEP ROW including {_p}, which that "
              f"control reproduced in every field. NOT bold, NOT promoted. "
              f"docs/ledger_verdicts.md#{{A}}.")
for _ln, (_p, _arm) in {329: ("L316", "OC"), 330: ("L318", "JT")}.items():
    V[_ln] = (f"NEW CELL at eval.max_steps 400: the registered-axis {_arm} arm, c_gain 0.3 -> "
              f"0.0, every other key identical to {_p}'s. Against the 400-step parent the obstacle "
              f"channel and the SINGULAR episode-axis fraction both rise. NOT COMPARABLE TO ANY "
              f"200-STEP ROW including {_p}; A1 was scored at 200 and its verdict stands. NOT "
              f"bold. docs/ledger_verdicts.md#{{A}}.")
